# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kseniya Lifanova
email: hello@kseniya.io
description: "This is the portfolio website for Kseniya Lifanova, a freelance web designer and front end web developer in Syracuse, NY."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: kseniya292
github_username:  kseniya292

# Build settings
markdown: kramdown

# Collections
collections:
  projects:
    output: true
    permalink: /web-projects/:path/